output "lakehouse_bucket_url" {
  value       = google_storage_bucket.lakehouse_bucket.url
  description = "GCS bucket URL"
}

output "databricks_gcp_sa_email" {
  value       = databricks_storage_credential.external_storage_credential.databricks_gcp_service_account[0].email
  description = "Service Account email generated by Databricks for WIF"
}

output "bronze_catalog_id" {
  value = databricks_catalog.bronze.id
}

output "silver_catalog_id" {
  value = databricks_catalog.silver.id
}

output "gold_catalog_id" {
  value = databricks_catalog.gold.id
}