name: "Terraform Deployment"
# This workflow is triggered on pushes to the main branch and pull requests targeting the main branch.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    # Set default working directory to 'infra' for all 'run' commands
    defaults:
      run:
        working-directory: src/infra/terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        working-directory: src/infra/terraform

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: src/infra/terraform

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: src/infra/terraform

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        working-directory: src/infra/terraform
        continue-on-error: true

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
        working-directory: src/infra/terraform